//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DentistAppointmentSystem.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_APPOINTMENTS
    {
        public int ID { get; set; }
        public System.DateTime DateAndTime { get; set; }
        public short DoctorID { get; set; }
        public short PatientID { get; set; }
        public byte DepartmentID { get; set; }
    
        public virtual TBL_DEPARTMENTS TBL_DEPARTMENTS { get; set; }
        public virtual TBL_DOCTORS TBL_DOCTORS { get; set; }
        public virtual TBL_PATIENTS TBL_PATIENTS { get; set; }
    }
}
