//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DentistAppointmentSystem.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_ADMINS
    {
        public short ID { get; set; }
        public short UserID { get; set; }
    
        public virtual TBL_USERS TBL_USERS { get; set; }
    }
}
